backend:
  name: github
  repo: jenkins-infra/stories
  branch: main
  use_graphql: true
  site_domain: stories.jenkins.io
  open_authoring: true

display_url: https://stories.jenkins.io
publish_mode: editorial_workflow

media_folder: "static/media"
public_folder: "/media"

collections:
  - name: user-story
    label: User Stories
    label_singular: User Story
    extension: yaml
    format: frontmatter
    folder: src/user-story
    path: '{{post_name}}/index'
    slug: 'index'
    media_folder: ''
    public_folder: ''
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Post Name (slug)
        name: post_name
        widget: string
      - label: Authored By
        name: authored_by
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
        date_format: 'YYYY-MM-DD'
        time_format: 'HH:mm:ss'
        format: 'YYYY-MM-DDTHH:mm.SSSZ'
      - label: Tag Line
        name: tag_line
        widget: text
      - label: Image
        name: image
        widget: image
      - label: Metadata
        name: metadata
        widget: "object"
        collapsed: false
        fields:
        - label: Organization
          name: organization
          widget: string
        - label: Industries
          name: industries
          widget: list
        - label: Programming Languages
          name: programming_languages
          widget: list
        - label: Platforms
          name: platforms
          widget: list
        - label: Version Control Systems
          name: version_control_systems
          widget: list
        - label: Build Tools
          name: build_tools
          widget: list
        - label: Community Supports
          name: community_supports
          widget: list
      - label: Testimonals
        name: quotes
        widget: list
        collapsed: true
        fields:
          - label: From
            name: from
            type: string
          - label: Content
            name: content
            type: text
          - label: Image
            name: image
            widget: image
      - label: Map Data
        name: map
        widget: "object"
        collapsed: true
        fields:
          - label: Author
            name: authored_by
            widget: string
          - label: Location
            name: location
            widget: string
          - label: GeoJSON
            name: geojson
            widget: map
            type: Point
            decimals: 7
      - label: Body
        name: body_content
        widget: "object"
        collapsed: false
        fields:
        - label: Title
          name: title
          widget: string
        - label: Paragaphs
          name: paragraphs
          widget: list
          allow_add: true
          field:
            label: Body
            name: paragraph
            widget: markdown
